### ISSUE TITLE
Enum serialization does not work anymore

### ISSUE THREAD

**Issue by Pauleing** [enioka-Haute-Couture/jqm#554]

**Comment by marcanpilami** [comment]
Actually not an enum or serialization issue. Due to one of the last remains of the OSGi attempts in the code - a weird sepration of the Query interface and its implementation (which is kinda weird, since the Query is by nature a DTO, but it existed to allow auto-execution of the query with different client implementations in OSGi).

I'll try to clean up the mess - going back to 2.2 code should be OK in this case.
